version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1" # Limita a 50% de 1 núcleo
          memory: "512M" # Limita a 512MB de RAM
volumes:
  mysql_data:
