name: Deploy na EC2

on:
  push:
    branches:
      - main  # Altere para sua branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Conectar na EC2 e executar o deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            ./deploy.sh
